org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.daemon=true
org.gradle.parallel=true

mod_version=4.1.6
mod_id=ironfurnaces
mod_name=Iron Furnaces
mod_license=GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
mod_group_id=ironfurnaces
mod_authors=Qelifern (pizzaatime), XenoMustache, Clefal
mod_description=IronFurnaces introduces a selection of metal furnaces, offering different tiers to fulfill your smelting needs effortlessly.
mod_issue=https://github.com/TUsama/Whats-Your-Build/issues
deps.fabric_loader=0.16.10
deps.fzzy_config_version = 0.7.5
deps.lib_version=2.0.17



